# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('condition', 'Condición'), ('availability', 'Disponibilidad')], db_index=True, max_length=20)),
                ('severity', models.PositiveSmallIntegerField(default=0, help_text='Higher is worse; orders them')),
                ('color', models.CharField(default='#888888', max_length=9)),
                ('requires_action', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('measurable', models.BooleanField(default=True, help_text='Availability only: can a reading be taken in this state')),
                ('notify_roles', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['kind', 'severity'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TechniqueStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('display_name', models.CharField(blank=True, help_text='Overrides the status name for this technique only', max_length=60)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thresholds.status')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechniqueStatusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('statuses', models.ManyToManyField(related_name='profiles', through='thresholds.TechniqueStatusOption', to='thresholds.status')),
                ('technique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_profile', to='measurements.technique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='techniquestatusoption',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='thresholds.techniquestatusprofile'),
        ),
        migrations.CreateModel(
            name='ThresholdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('equipment_type', 'Tipo de equipo'), ('asset_group_kind', 'Tipo de conjunto'), ('equipment', 'Equipo'), ('point', 'Punto')], db_index=True, max_length=20)),
                ('scope_ref_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('magnitude_code', models.SlugField(max_length=40)),
                ('unit_code', models.CharField(max_length=20)),
                ('aggregation', models.CharField(default='rms', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('rationale', models.TextField(blank=True, help_text='Why this override exists')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('machine_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='thresholds.machineclass')),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.ForeignKey(limit_choices_to={'kind': 'condition'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thresholds.status')),
                ('threshold_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='thresholds.thresholdset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='thresholdset',
            name='standard',
            field=models.ForeignKey(blank=True, help_text='Empty means a hand-written criterion, which always competes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='thresholds.thresholdstandard'),
        ),
        migrations.AddField(
            model_name='machineclass',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_classes', to='thresholds.thresholdstandard'),
        ),
        migrations.AlterUniqueTogether(
            name='techniquestatusoption',
            unique_together={('profile', 'status')},
        ),
        migrations.AddIndex(
            model_name='thresholdset',
            index=models.Index(fields=['company', 'magnitude_code', 'scope', 'scope_ref_id'], name='thresholds__company_8e4db9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='machineclass',
            unique_together={('standard', 'code')},
        ),
    ]
