# Generated by Django 5.2.17 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdstandard',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='standards', to='measurements.technique'),
        ),
    ]
