# Generated by Django 5.2.17 on 2026-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresholds', '0002_thresholdstandard_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineclass',
            name='mounting',
            field=models.CharField(choices=[('any', 'Cualquiera'), ('rigid', 'Rígida'), ('flexible', 'Flexible')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='machineclass',
            name='power_max_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='machineclass',
            name='power_min_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
