# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('deployment', models.CharField(choices=[('hosted', 'Alojado por nosotros'), ('on_premise', 'Base de datos del cliente')], default='hosted', max_length=20)),
                ('database_url', models.TextField(blank=True)),
                ('database_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_id', models.CharField(max_length=40, unique=True)),
                ('token', models.TextField()),
                ('plan', models.CharField(max_length=40)),
                ('issued_at', models.DateField()),
                ('valid_until', models.DateField(db_index=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=15)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licensing.tenant')),
            ],
            options={
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issued', 'Emitida'), ('renewed', 'Renovada'), ('revoked', 'Revocada'), ('blocked', 'Acceso bloqueado'), ('degraded', 'Solo lectura'), ('limit_reached', 'Límite alcanzado'), ('fingerprint_mismatch', 'Base de datos distinta')], db_index=True, max_length=30)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='licensing.tenant')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
