# Generated by Django 5.2.17 on 2026-09-27 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_equipment_equipment_type'),
        ('core', '0002_initial'),
        ('media', '0007_signature_and_survey_kinds'),
        ('services', '0006_order_standard'),
        ('workday', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(blank=True, help_text='Nombre de la actividad y/o trabajo', max_length=200)),
                ('holder', models.CharField(blank=True, help_text='Titular de la actividad', max_length=160)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('risk_category', models.CharField(blank=True, choices=[('high', 'Alto'), ('medium', 'Mediano'), ('low', 'Bajo')], max_length=10)),
                ('ppe', models.TextField(blank=True, help_text='EPP')),
                ('tools', models.TextField(blank=True, help_text='Equipos y herramientas')),
                ('steps', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetgroup')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.serviceorder')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workday.workday')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('production_engineer', 'Ingeniero de producción'), ('service_leader', 'Líder encargado del servicio'), ('plant_supervisor', 'Supervisor de planta'), ('crew', 'Personal ejecutor')], max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('position', models.CharField(blank=True, help_text='Cargo', max_length=120)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='workday.servicejob')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='SafetyPermit',
        ),
    ]
