# Generated by Django 5.2.17 on 2026-09-24 22:03

from django.db import migrations, models


SYSTEM_ROLES = (
    "platform_admin", "company_admin", "engineer", "planner",
    "technician", "external_inspector", "client_viewer",
)


def base_on_themselves(apps, schema_editor):
    """A system role behaves as itself; only company-made roles borrow one."""
    Role = apps.get_model("security", "Role")
    alias = schema_editor.connection.alias
    for role in Role.objects.using(alias).all():
        role.base_role = role.code if role.code in SYSTEM_ROLES else "client_viewer"
        role.save(update_fields=["base_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'Turno A'), ('B', 'Turno B'), ('C', 'Turno C')], max_length=1),
        ),
        migrations.AddField(
            model_name='role',
            name='base_role',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='user',
            name='access_code_digest',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access_code_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(base_on_themselves, migrations.RunPython.noop),
    ]
