# Generated by Django 5.2.17 on 2026-09-27 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_label", models.CharField(blank=True, max_length=160)),
                ("kind", models.CharField(db_index=True, max_length=20)),
                ("event", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=300)),
                ("path", models.CharField(blank=True, max_length=200)),
                ("method", models.CharField(blank=True, max_length=8)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(fields=["company", "-at"], name="activity_ac_company_f60c53_idx"),
                    models.Index(fields=["company", "user", "-at"], name="activity_ac_company_d6d174_idx"),
                ],
            },
        ),
    ]
