# Generated by Django 5.2.17 on 2026-09-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alignment', '0002_seed_tolerances'),
        ('assets', '0010_seed_lubrication_type'),
        ('core', '0002_initial'),
        ('diagnostics', '0003_electrical_fluting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_types', models.JSONField(default=list, help_text="One or more of WORK_TYPES's codes")),
                ('other_description', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('shift_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('spare_parts_used', models.TextField(blank=True)),
                ('client_work_order', models.CharField(blank=True, max_length=60)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alignment_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alignment.alignmentrecord')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_records', to='assets.assetgroup')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to='assets.equipment')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diagnostics.equipmentlogentry')),
            ],
            options={
                'ordering': ['-shift_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_name', models.CharField(blank=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='maintenance.workrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
