# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('core', '0002_initial'),
        ('measurements', '0001_initial'),
        ('thresholds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='MPd-AV-N°006-13', max_length=40)),
                ('client_work_order', models.CharField(blank=True, help_text='OT del ERP del cliente (JD Edwards, SAP...)', max_length=40)),
                ('external_refs', models.JSONField(blank=True, default=dict)),
                ('scheduled_from', models.DateField()),
                ('scheduled_to', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Programada'), ('in_progress', 'En ejecución'), ('done', 'Ejecutada'), ('cancelled', 'Anulada')], default='planned', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('lead_analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assets.plant')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.technique')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='assets.plant')),
            ],
            options={
                'unique_together': {('plant', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_days', models.PositiveSmallIntegerField(choices=[(30, '30 días'), (60, '60 días'), (90, '90 días'), (120, '120 días'), (150, '150 días'), (180, '180 días'), (365, '365 días')], default=30)),
                ('scope', models.CharField(default='area', max_length=20)),
                ('scope_ref_id', models.CharField(blank=True, max_length=40)),
                ('planned_points', models.PositiveIntegerField(default=0)),
                ('planned_mandays', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.technique')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='services.serviceplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_at', models.DateTimeField(db_index=True)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('availability_status', models.ForeignKey(blank=True, help_text="Declared by the technician, from the technique's profile", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thresholds.status')),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='assets.equipment')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='measurements.instrument')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='services.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='VisitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead_analyst', 'Inspector analista'), ('assistant', 'Asistente'), ('supervisor', 'Supervisor'), ('client_witness', 'Testigo del cliente')], default='lead_analyst', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_participations', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='services.servicevisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicevisit',
            index=models.Index(fields=['company', 'equipment', '-visited_at'], name='services_se_company_25cff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitparticipant',
            unique_together={('visit', 'user')},
        ),
    ]
