# Generated by Django 5.2.17 on 2026-09-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_faultmode_is_active_alter_faultmode_iso_reference'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='fault_modes',
            field=models.ManyToManyField(blank=True, related_name='visits', to='diagnostics.faultmode'),
        ),
    ]
