# Generated by Django 5.2.17 on 2026-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_seed_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='other_fault',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
