# Generated by Django 5.2.17 on 2026-09-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_visit_other_fault'),
        ('thresholds', '0003_machine_class_power_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='thresholds.thresholdstandard'),
        ),
    ]
