# Generated by Django 5.2.17 on 2026-09-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_drop_legacy_kind_column'),
        ('core', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('unit_code', models.CharField(blank=True, max_length=20)),
                ('technique_code', models.SlugField(blank=True, max_length=30)),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Equipment types; empty means all')),
                ('is_cumulative', models.BooleanField(default=False, help_text='Running hours only grow; a drop means it was reset')),
                ('decimals', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OperatingReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.CharField(blank=True, help_text='For codes such as ISO 4406 cleanliness', max_length=120)),
                ('taken_at', models.DateTimeField(db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_readings', to='assets.equipment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='operating_data.operatingparameter')),
                ('service_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_readings', to='services.servicevisit')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'equipment', '-taken_at'], name='operating_d_company_40a257_idx')],
                'unique_together': {('service_visit', 'parameter')},
            },
        ),
    ]
