# Generated by Django 5.2.17 on 2026-09-25 15:15

from django.db import migrations, models

from modules.operating_data.domain.precision import decimals_for


def whole_numbers(apps, schema_editor):
    """The customer reads operating data as whole numbers (V3-30); the power
    factor keeps two decimals because it lives between 0 and 1."""
    alias = schema_editor.connection.alias
    Parameter = apps.get_model("operating_data", "OperatingParameter")
    for parameter in Parameter.objects.using(alias).all():
        parameter.decimals = decimals_for(parameter.code)
        parameter.save(using=alias, update_fields=["decimals"])


class Migration(migrations.Migration):

    dependencies = [
        ('operating_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(whole_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='operatingparameter',
            name='decimals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
