"""Signing in with a personal code, the way a field technician does.

Three shifts share one tablet in the plant, and typing an e-mail and a long
password with gloves on is how a crew ends up sharing one login — which is
the end of knowing who recorded what. A personal code keeps every reading
signed by the person who took it.

Three decisions carry the security of this, and all three matter:

- the code is generated by the server, never chosen: people pick 123456;
- it is shown once and only a keyed digest is stored, so a copy of the
  database is not a list of working codes;
- the login is throttled per address, because an eight-character code is
  only as strong as the number of guesses it allows.
"""

from __future__ import annotations

import secrets

from django.utils import timezone
from django.utils.crypto import salted_hmac
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.throttling import ScopedRateThrottle
from rest_framework.views import APIView

from modules.core.infrastructure.audit import record
from modules.security.application.access import build_actor
from modules.security.domain.actor import Role, behaviour_of
from modules.security.models import Membership, User

# No 0/O, 1/I/L: a code read off a label in a dim plant room gets misread.
ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
CODE_LENGTH = 8
# Only the roles that record field data sign in by code. A manager's access
# goes through the corporate credential, as the access matrix asks.
FIELD_BEHAVIOURS = frozenset({Role.TECHNICIAN, Role.EXTERNAL_INSPECTOR})


def digest(code: str) -> str:
    """Deterministic, so the login can find the person; keyed, so it cannot be
    reversed or precomputed without the server's secret."""
    return salted_hmac("security.access_code", code.strip().upper()).hexdigest()


class AccessCodeIssueView(APIView):
    """`POST users/<id>/access-code/` — issues a fresh code, replacing the old.

    The plaintext is in this response and nowhere else, ever. Losing it means
    issuing a new one, which also revokes the lost code.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, user_id: int):
        actor = build_actor(request.user, request.company_id)
        if not actor.has("security.manage_access_code"):
            raise PermissionDenied("Falta el permiso security.manage_access_code")

        membership = (
            Membership.objects.filter(company_id=request.company_id, user_id=user_id)
            .select_related("user", "role")
            .first()
        )
        if membership is None:
            return Response({"type": "not_found", "status": 404}, status=404)
        if behaviour_of(membership.role.base_role or membership.role.code) not in FIELD_BEHAVIOURS:
            raise ValidationError(
                "El código de acceso es para personal de campo; este rol entra "
                "con su credencial corporativa"
            )

        code = _unique_code()
        user = membership.user
        user.access_code_digest = digest(code)
        user.access_code_set_at = timezone.now()
        user.save(update_fields=["access_code_digest", "access_code_set_at"])
        # The code itself is never logged: an audit trail that stores it is a
        # second place to steal it from.
        record(request, "user.access_code_issued", object_type="user", object_id=user.id)
        return Response({"code": code, "issued_at": user.access_code_set_at}, status=201)

    def delete(self, request, user_id: int):
        """Revokes the code without issuing another: a lost tablet, a leaver."""
        actor = build_actor(request.user, request.company_id)
        if not actor.has("security.manage_access_code"):
            raise PermissionDenied("Falta el permiso security.manage_access_code")
        user = User.objects.filter(
            id=user_id, memberships__company_id=request.company_id
        ).first()
        if user is None:
            return Response({"type": "not_found", "status": 404}, status=404)
        user.access_code_digest = None
        user.access_code_set_at = None
        user.save(update_fields=["access_code_digest", "access_code_set_at"])
        record(request, "user.access_code_revoked", object_type="user", object_id=user.id)
        return Response(status=204)


class CodeLoginView(APIView):
    """`POST auth/code-login/` — a personal code in, a session out."""

    permission_classes = [AllowAny]
    authentication_classes: list = []
    throttle_classes = [ScopedRateThrottle]
    throttle_scope = "code_login"

    def post(self, request):
        from rest_framework_simplejwt.tokens import RefreshToken

        code = (request.data.get("code") or "").strip().upper()
        # Same answer for "no such code" and "inactive user": telling them apart
        # tells a guesser which codes are worth trying again later.
        refused = Response(
            {"type": "invalid_code", "title": "Código no válido", "status": 401}, status=401
        )
        if len(code) != CODE_LENGTH:
            return refused

        user = User.objects.filter(access_code_digest=digest(code), is_active=True).first()
        membership = (
            Membership.objects.filter(user=user).select_related("role").first() if user else None
        )
        if user is None or membership is None or behaviour_of(
            membership.role.base_role or membership.role.code
        ) not in FIELD_BEHAVIOURS:
            record(request, "auth.code_login_failed", object_type="auth")
            return refused

        request.company_id = membership.company_id
        record(request, "auth.code_login", object_type="user", object_id=user.id, actor=user)
        refresh = RefreshToken.for_user(user)
        return Response({"access": str(refresh.access_token), "refresh": str(refresh)})


def _unique_code() -> str:
    """A fresh code no one else holds. Collisions are rare, not impossible."""
    for _ in range(8):
        code = "".join(secrets.choice(ALPHABET) for _ in range(CODE_LENGTH))
        if not User.objects.filter(access_code_digest=digest(code)).exists():
            return code
    raise ValidationError("No se pudo generar un código único; inténtalo de nuevo")
