# Generated by Django 5.2.17 on 2026-09-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_drop_legacy_kind_column'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameplateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rated_power_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Potencia nominal. Decide la clase ISO y con ella los límites', max_digits=10, null=True)),
                ('rated_rpm', models.PositiveIntegerField(blank=True, null=True)),
                ('rated_voltage_v', models.PositiveIntegerField(blank=True, null=True)),
                ('rated_current_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('frame_size', models.CharField(blank=True, max_length=40)),
                ('mounting', models.CharField(blank=True, choices=[('rigid', 'Rígida'), ('flexible', 'Flexible')], help_text='Cimentación rígida o flexible, según ISO 10816-3', max_length=10)),
                ('bearing_de', models.CharField(blank=True, help_text='Rodamiento lado acople', max_length=40)),
                ('bearing_nde', models.CharField(blank=True, help_text='Rodamiento lado libre', max_length=40)),
                ('lubricant', models.CharField(blank=True, max_length=80)),
                ('lubricant_interval_h', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('nameplate_photo', 'Foto de placa'), ('datasheet', 'Ficha técnica'), ('manual', 'Manual'), ('estimated', 'Estimado')], default='nameplate_photo', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nameplate', to='assets.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
