# Generated by Django 5.2.17 on 2026-09-26 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_builtin_kind_layouts'),
        ('core', '0002_initial'),
        ('services', '0005_visit_other_fault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopographyElementReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_label', models.CharField(help_text="Su número en el plano, p. ej. 'R3'", max_length=40)),
                ('level_h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('level_v', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parallel_h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parallel_v', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observation', models.TextField(blank=True)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topography_readings', to='assets.assetgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topography_readings', to='services.servicevisit')),
            ],
            options={
                'ordering': ['element_label'],
            },
        ),
    ]
