# Generated by Django 5.2.17 on 2026-09-26 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_builtin_kind_layouts'),
        ('core', '0002_initial'),
        ('diagnostics', '0002_faultmode_is_active_alter_faultmode_iso_reference'),
        ('services', '0005_visit_other_fault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_label', models.CharField(blank=True, help_text='El motriz del acople', max_length=80)),
                ('driven_label', models.CharField(blank=True, help_text='El conducido del acople', max_length=80)),
                ('rpm', models.DecimalField(decimal_places=1, max_digits=8)),
                ('instrument', models.CharField(blank=True, max_length=120)),
                ('before_angular_h', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('before_parallel_h', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('before_angular_v', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('before_parallel_v', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('after_angular_h', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('after_parallel_h', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('after_angular_v', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('after_parallel_v', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('backlash_within_tolerance', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tolerance_parallel_mm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tolerance_angular_mm_per_100mm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alignment_records', to='assets.assetgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnosed_fault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='diagnostics.faultmode')),
                ('service_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_records', to='services.servicevisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlignmentTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rpm_ceiling', models.PositiveIntegerField(blank=True, help_text='RPM por debajo de la cual aplica; vacío = sin techo', null=True)),
                ('parallel_mm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('angular_mm_per_100mm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('asset_group', models.ForeignKey(blank=True, help_text='Vacío: tolerancia global por RPM. Con conjunto: la sobrescribe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_tolerances', to='assets.assetgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['asset_group_id', models.OrderBy(models.F('rpm_ceiling'), nulls_last=True)],
            },
        ),
    ]
