# Generated by Django 5.2.17 on 2026-09-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0002_seed_tolerances'),
        ('thresholds', '0003_machine_class_power_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentrecord',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alignment_records', to='thresholds.thresholdstandard'),
        ),
        migrations.AddField(
            model_name='alignmenttolerance',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_tiers', to='thresholds.thresholdstandard'),
        ),
    ]
