# Generated by Django 5.2.17 on 2026-09-27 02:08

import django.db.models.deletion
from django.db import migrations, models


def keep_two_screens(apps, schema_editor):
    """Records saved before the aligner was asked kept one screen per phase:
    they read as "other aligner", so their images stay where they were."""
    Record = apps.get_model("alignment", "AlignmentRecord")
    Record.objects.using(schema_editor.connection.alias).update(aligner="other")


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0004_tiers_as_norma'),
        ('thresholds', '0003_machine_class_power_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentrecord',
            name='aligner',
            field=models.CharField(choices=[('skf', 'Alineador SKF'), ('other', 'Otro alineador')], default='skf', max_length=10),
        ),
        migrations.AddField(
            model_name='alignmentrecord',
            name='scale_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alignmenttolerance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='thresholds.status'),
        ),
        migrations.AlterField(
            model_name='alignmenttolerance',
            name='angular_mm_per_100mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='alignmenttolerance',
            name='parallel_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.RunPython(keep_two_screens, migrations.RunPython.noop),
    ]
