# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('measurements', '0001_initial'),
        ('services', '0001_initial'),
        ('thresholds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='condition_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'condition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thresholds.status'),
        ),
        migrations.AddField(
            model_name='reading',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='measurements.instrument'),
        ),
        migrations.AddField(
            model_name='reading',
            name='magnitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.magnitude'),
        ),
        migrations.AddField(
            model_name='reading',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reading',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='assets.measurementpoint'),
        ),
        migrations.AddField(
            model_name='reading',
            name='service_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='services.servicevisit'),
        ),
        migrations.AddField(
            model_name='reading',
            name='threshold_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thresholds.thresholdset'),
        ),
        migrations.AddField(
            model_name='readingbatch',
            name='service_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='services.servicevisit'),
        ),
        migrations.AddField(
            model_name='magnitude',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magnitudes', to='measurements.technique'),
        ),
        migrations.AddField(
            model_name='reading',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.unit'),
        ),
        migrations.AddField(
            model_name='magnitude',
            name='default_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['company', 'point', 'magnitude', '-taken_at'], name='measurement_company_6416fa_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['company', '-taken_at'], name='measurement_company_a04c71_idx'),
        ),
    ]
