# Generated by Django 5.2.17 on 2026-09-18 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_train_component_layout'),
        ('core', '0002_initial'),
        ('diagnostics', '0002_faultmode_is_active_alter_faultmode_iso_reference'),
        ('measurements', '0002_initial'),
        ('media', '0003_media_equipment_index'),
        ('services', '0002_servicevisit_fault_modes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField(db_index=True)),
                ('spectrum_type', models.CharField(choices=[('velocity', 'Velocidad'), ('envelope', 'Envolvente'), ('acceleration', 'Aceleración'), ('demodulation', 'Demodulación'), ('waveform', 'Forma de onda')], default='velocity', max_length=20)),
                ('fmin_hz', models.FloatField(blank=True, null=True)),
                ('fmax_hz', models.FloatField(blank=True, null=True)),
                ('lines', models.PositiveIntegerField(blank=True, null=True)),
                ('rpm_at_capture', models.FloatField(blank=True, null=True)),
                ('window', models.CharField(blank=True, max_length=20)),
                ('averages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_key', models.CharField(blank=True, max_length=300)),
                ('peak_hz', models.FloatField(blank=True, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('diagnosis', models.ManyToManyField(blank=True, related_name='spectra', to='diagnostics.faultmode')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectra', to='media.mediaasset')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='assets.measurementpoint')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectra', to='measurements.reading')),
                ('service_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectra', to='services.servicevisit')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='measurements.unit')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['company', 'point', 'spectrum_type', '-taken_at'], name='measurement_company_a3d69f_idx')],
            },
        ),
    ]
