# Generated by Django 5.2.17 on 2026-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_spectrum'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbatch',
            name='reading_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
