# Generated by Django 5.2.17 on 2026-09-22 21:40

from django.db import migrations, models


# How each shipped magnitude is actually read, from the source reports:
# velocity on three axes of a bearing, everything else once on it.
PER_BEARING = {
    "env_accel": "{n} ENV",
    "temp": "TEMP {n}",
    "delta_temp": "ΔT {n}",
    "delta_temp_ambient": "ΔTA {n}",
    "us_db": "0{n}-UT",
    "viscosity_40": "VISC {n}",
    "water_ppm": "H2O {n}",
    "dielectric_kv": "KV {n}",
}


def mark_per_bearing(apps, schema_editor):
    Magnitude = apps.get_model("measurements", "Magnitude")
    alias = schema_editor.connection.alias
    for code, short in PER_BEARING.items():
        Magnitude.objects.using(alias).filter(code=code).update(
            per_axis=False, short_code=short
        )


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_batch_reading_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnitude',
            name='per_axis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='magnitude',
            name='short_code',
            field=models.CharField(blank=True, help_text='How the sheet names the row: "{n} ENV", "TEMP {n}", "UT {n}"', max_length=16),
        ),
        migrations.RunPython(mark_per_bearing, migrations.RunPython.noop),
    ]
