# Generated by Django 5.2.17 on 2026-09-22 21:46

from django.db import migrations, models


# What each service's report leads with.
HEADLINES = {
    "vibration": "vel_rms",
    "thermography": "temp",
    "ultrasound": "thickness_mm",
    "oil_analysis": "viscosity_40",
    "insulating_oil": "dielectric_kv",
}


def set_headlines(apps, schema_editor):
    Technique = apps.get_model("measurements", "Technique")
    alias = schema_editor.connection.alias
    for code, magnitude in HEADLINES.items():
        Technique.objects.using(alias).filter(code=code).update(headline_magnitude=magnitude)


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_magnitude_per_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='headline_magnitude',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.RunPython(set_headlines, migrations.RunPython.noop),
    ]
