# Generated by Django 5.2.17 on 2026-09-25 15:17

from django.db import migrations, models

from modules.measurements.domain.magnitude_order import display_order_for


def sheet_order(apps, schema_editor):
    """Velocity, acceleration, envelope, temperature — the sheet's order."""
    alias = schema_editor.connection.alias
    Magnitude = apps.get_model("measurements", "Magnitude")
    for magnitude in Magnitude.objects.using(alias).all():
        magnitude.display_order = display_order_for(magnitude.code)
        magnitude.save(using=alias, update_fields=["display_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_ndt_thickness_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnitude',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=900),
        ),
        migrations.RunPython(sheet_order, migrations.RunPython.noop),
    ]
