# Generated by Django 5.2.17 on 2026-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0008_magnitude_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='spectrum_type',
            field=models.CharField(choices=[('velocity', 'Velocidad'), ('envelope', 'Envolvente'), ('acceleration', 'Aceleración'), ('demodulation', 'Demodulación'), ('waveform', 'Forma de onda'), ('waterfall', 'Cascada')], default='velocity', max_length=20),
        ),
    ]
