# Generated by Django 5.2.17 on 2026-09-25 15:59

from django.db import migrations, models

from modules.measurements.domain.families import family_for


def classify(apps, schema_editor):
    """MPd Predictivo, END, or internal: the customer's two families (V3-19)."""
    alias = schema_editor.connection.alias
    Technique = apps.get_model("measurements", "Technique")
    for technique in Technique.objects.using(alias).all():
        technique.family = family_for(technique.code)
        technique.save(using=alias, update_fields=["family"])


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0009_spectrum_waterfall_and_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='family',
            field=models.CharField(choices=[('mpd', 'MPd Predictivo'), ('ndt', 'END'), ('internal', 'Interno')], db_index=True, default='mpd', max_length=10),
        ),
        migrations.RunPython(classify, migrations.RunPython.noop),
    ]
