# Generated by Django 5.2.17 on 2026-09-25 17:00

from django.db import migrations, models

from modules.measurements.domain.acceleration import ACCELERATION as SPEC
from modules.measurements.domain.magnitude_order import display_order_for


def add_acceleration(apps, schema_editor):
    """Global acceleration in g RMS, between velocity and envelope (V3-11).

    A fresh database has no catalogue yet; the seed creates it there."""
    alias = schema_editor.connection.alias
    Technique = apps.get_model("measurements", "Technique")
    Unit = apps.get_model("measurements", "Unit")
    Magnitude = apps.get_model("measurements", "Magnitude")
    technique = Technique.objects.using(alias).filter(code=SPEC.technique).first()
    unit = Unit.objects.using(alias).filter(code=SPEC.unit).first()
    if technique is None or unit is None:
        return
    Magnitude.objects.using(alias).update_or_create(
        code=SPEC.code,
        defaults={
            "technique": technique, "name": SPEC.name_es, "default_unit": unit,
            "default_aggregation": SPEC.aggregation, "decimals": SPEC.decimals,
            "per_axis": SPEC.per_axis, "higher_is_worse": SPEC.higher_is_worse,
            "template_only": SPEC.template_only, "display_order": display_order_for(SPEC.code),
            "translations": {"name": {"es": SPEC.name_es, "en": SPEC.name_en}},
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0010_technique_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnitude',
            name='template_only',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_acceleration, migrations.RunPython.noop),
    ]
