# Generated by Django 5.2.17 on 2026-09-26 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0011_acceleration_in_g'),
        ('media', '0005_train_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset'),
        ),
    ]
