# Generated by Django 5.2.17 on 2026-09-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0013_thermography_ir_tmax'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='close_requirement',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
