# Generated by Django 5.2.17 on 2026-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0014_technique_close_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='evidence_only',
            field=models.BooleanField(default=False),
        ),
    ]
