# Generated by Django 5.2.17 on 2026-09-26 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_alter_equipment_equipment_type'),
        ('core', '0002_initial'),
        ('services', '0005_visit_other_fault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UTIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('crack', 'Fisura'), ('undercut', 'Socavación'), ('other', 'Otra')], max_length=20)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('position', models.CharField(blank=True, help_text='e.g. "P3, lado mando"', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ut_indications', to='assets.equipment')),
                ('service_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ut_indications', to='services.servicevisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
