# Generated by Django 5.2.17 on 2026-09-27 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_equipment_equipment_type'),
        ('core', '0002_initial'),
        ('media', '0007_signature_and_survey_kinds'),
        ('services', '0006_order_standard'),
        ('ut_rollers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utindication',
            name='side',
            field=models.CharField(blank=True, choices=[('drive', 'Lado mando'), ('transmission', 'Lado transmisión')], max_length=15),
        ),
        migrations.CreateModel(
            name='JournalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('drive', 'Lado mando'), ('transmission', 'Lado transmisión')], max_length=15)),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('external_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('access', models.CharField(choices=[('ok', 'Con acceso'), ('covered', 'Tapado (sin acceso)'), ('no_access', 'Sin acceso')], default='ok', max_length=15)),
                ('access_note', models.CharField(blank=True, help_text='Por qué no hubo acceso', max_length=200)),
                ('state_text', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ut_journals', to='assets.equipment')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.serviceorder')),
            ],
            options={
                'ordering': ['equipment__order_in_group', 'side'],
                'unique_together': {('service_order', 'equipment', 'side')},
            },
        ),
        migrations.CreateModel(
            name='RollerGroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conclusions', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.assetgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.serviceorder')),
            ],
            options={
                'unique_together': {('service_order', 'asset_group')},
            },
        ),
    ]
