# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Fotografía de servicio'), ('spectrum_image', 'Captura de espectro'), ('thermogram', 'Termograma'), ('ultrasound_capture', 'Captura de ultrasonido'), ('blueprint', 'Plano'), ('nameplate', 'Placa de características'), ('document', 'Documento'), ('report_pdf', 'Reporte PDF')], db_index=True, max_length=30)),
                ('owner_type', models.CharField(db_index=True, max_length=40)),
                ('owner_id', models.PositiveBigIntegerField(db_index=True)),
                ('original_key', models.CharField(max_length=300)),
                ('original_format', models.CharField(max_length=20)),
                ('original_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=120)),
                ('exif', models.JSONField(blank=True, default=dict)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('processing_state', models.CharField(choices=[('pending', 'Pendiente'), ('uploading', 'Subiendo'), ('processing', 'Procesando'), ('done', 'Listo'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('thermal_meta', models.JSONField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
        ),
    ]
