# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['company', 'owner_type', 'owner_id'], name='media_media_company_b0deca_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['processing_state', 'created_at'], name='media_media_process_819eca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaasset',
            unique_together={('company', 'checksum_sha256')},
        ),
    ]
