# Generated by Django 5.2.17 on 2026-09-18 01:01

from django.conf import settings
from django.db import migrations, models


def backfill_equipment(apps, schema_editor):
    """Media uploaded before the gallery existed still belongs to a machine.

    Every query is pinned to the database being migrated: a tenant runs on its
    own connection and the default alias is the control plane, which has no
    media at all.
    """
    alias = schema_editor.connection.alias
    MediaAsset = apps.get_model("media", "MediaAsset")
    ServiceVisit = apps.get_model("services", "ServiceVisit")
    visits = {
        row["id"]: row
        for row in ServiceVisit.objects.using(alias).values("id", "equipment_id", "visited_at")
    }
    if not visits:
        return

    updates = []
    queryset = MediaAsset.objects.using(alias).filter(owner_type="visit", equipment_ref=None)
    for asset in queryset.iterator(chunk_size=1000):
        visit = visits.get(asset.owner_id)
        if visit is None:
            continue
        asset.equipment_ref = visit["equipment_id"]
        asset.captured_on = visit["visited_at"].date()
        updates.append(asset)
        if len(updates) >= 1000:
            MediaAsset.objects.using(alias).bulk_update(
                updates, ["equipment_ref", "captured_on"]
            )
            updates = []
    if updates:
        MediaAsset.objects.using(alias).bulk_update(updates, ["equipment_ref", "captured_on"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('media', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='captured_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='equipment_ref',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['company', 'equipment_ref', 'kind', '-created_at', '-id'], name='media_equipment_page_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['company', 'equipment_ref', '-created_at', '-id'], name='media_equipment_all_idx'),
        ),
        migrations.RunPython(backfill_equipment, migrations.RunPython.noop),
    ]
