# Generated by Django 5.2.17 on 2026-09-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('media', '0003_media_equipment_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaasset',
            unique_together={('company', 'checksum_sha256', 'owner_type', 'owner_id')},
        ),
    ]
