# Generated by Django 5.2.17 on 2026-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_asset_per_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('photo', 'Fotografía de servicio'), ('spectrum_image', 'Captura de espectro'), ('thermogram', 'Termograma'), ('ultrasound_capture', 'Captura de ultrasonido'), ('blueprint', 'Plano'), ('nameplate', 'Placa de características'), ('document', 'Documento'), ('report_pdf', 'Reporte PDF'), ('schematic', 'Esquema del conjunto'), ('site_photo', 'Foto del equipo')], db_index=True, max_length=30),
        ),
    ]
