# Generated by Django 5.2.17 on 2026-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_mediaasset_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('photo', 'Fotografía de servicio'), ('spectrum_image', 'Captura de espectro'), ('thermogram', 'Termograma'), ('ultrasound_capture', 'Captura de ultrasonido'), ('blueprint', 'Plano'), ('nameplate', 'Placa de características'), ('document', 'Documento'), ('report_pdf', 'Reporte PDF'), ('schematic', 'Esquema del conjunto'), ('site_photo', 'Foto del equipo'), ('alignment_before', 'Alineamiento · antes'), ('alignment_after', 'Alineamiento · después'), ('alignment_group', 'Alineamiento · conjunto'), ('alignment_observation', 'Alineamiento · observación'), ('topography_plan', 'Plano de topografía'), ('alignment_result', 'Alineamiento · resultado'), ('topography_schema', 'Esquema del conjunto (topografía)'), ('topography_box', 'Topografía · cuadro de medida'), ('signature', 'Firma')], db_index=True, max_length=30),
        ),
    ]
