# Generated by Django 5.2.17 on 2026-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('criticality', models.PositiveSmallIntegerField(default=3, help_text='1 highest')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('motor_pump', 'Motor-Bomba'), ('motor_compressor', 'Motor-Compresor'), ('motor_gearbox', 'Motor-Reductor'), ('motor_fan', 'Motor-Ventilador'), ('motor_blower', 'Motor-Soplador'), ('standalone', 'Equipo aislado')], default='standalone', max_length=30)),
                ('criticality', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.SlugField(help_text='Internal key. Always unique', max_length=60)),
                ('client_tag', models.CharField(blank=True, db_index=True, help_text='Customer TAG. Optional and NOT unique: sources repeat it across motor and pump', max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('motor', 'Motor'), ('pump', 'Bomba'), ('compressor', 'Compresor'), ('gearbox', 'Reductor'), ('fan', 'Ventilador'), ('blower', 'Soplador'), ('bearing_housing', 'Chumacera'), ('other', 'Otro')], max_length=30)),
                ('position_in_group', models.CharField(choices=[('driver', 'Motriz'), ('driven', 'Conducido'), ('intermediate', 'Intermedio')], default='driven', max_length=20)),
                ('monitoring_frequency', models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('on_demand', 'Bajo demanda')], default='monthly', max_length=20)),
                ('condition_updated_at', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('retired_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('side', models.CharField(choices=[('free_end', 'Lado libre'), ('coupling_end', 'Lado acople'), ('opposite_coupling', 'Lado opuesto a acople'), ('inboard', 'Interior'), ('outboard', 'Exterior'), ('custom', 'Otro')], default='custom', max_length=20)),
                ('axis', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical'), ('A', 'Axial'), ('N', 'Sin eje')], default='N', max_length=1)),
                ('point_type', models.CharField(choices=[('bearing', 'Rodamiento'), ('electrical', 'Eléctrico'), ('thermal', 'Térmico'), ('ultrasound', 'Ultrasonido'), ('lubrication', 'Lubricación'), ('process', 'Proceso')], default='bearing', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Derived: "1H", "3V"', max_length=20)),
                ('blueprint_x', models.FloatField(blank=True, null=True)),
                ('blueprint_y', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number', 'axis'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('timezone', models.CharField(default='America/Lima', max_length=64)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
