# Generated by Django 5.2.17 on 2026-09-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('core', '0001_initial'),
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='applied_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='thresholds.thresholdstandard'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='assets.assetgroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='availability_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'availability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thresholds.status'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition_status',
            field=models.ForeignKey(blank=True, help_text='Derived from the last evaluated reading', limit_choices_to={'kind': 'condition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thresholds.status'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='machine_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='thresholds.machineclass'),
        ),
        migrations.AddField(
            model_name='measurementpoint',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='measurementpoint',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='assets.equipment'),
        ),
        migrations.AddField(
            model_name='plant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='area',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assets.plant'),
        ),
        migrations.AddField(
            model_name='sector',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='assets.area'),
        ),
        migrations.AddField(
            model_name='sector',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assets.sector'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['company', 'client_tag'], name='assets_equi_company_51ee45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('company', 'asset_code')},
        ),
        migrations.AlterUniqueTogether(
            name='measurementpoint',
            unique_together={('equipment', 'number', 'axis')},
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('plant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='assetgroup',
            unique_together={('company', 'code')},
        ),
    ]
