# Generated by Django 5.2.17 on 2026-09-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroup',
            name='kind',
            field=models.CharField(default='standalone', max_length=30),
        ),
        migrations.CreateModel(
            name='AssetGroupKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssetGroupComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(help_text='As the report prints it: "MOTOR", "BOMBA"', max_length=60)),
                ('equipment_type', models.CharField(default='motor', max_length=30)),
                ('position', models.CharField(default='driver', max_length=20)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.assetgroupkind')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='kind_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='assets.assetgroupkind'),
        ),
        migrations.CreateModel(
            name='PointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('axis', models.CharField(default='H', max_length=1)),
                ('side', models.CharField(default='custom', max_length=20)),
                ('point_type', models.CharField(default='bearing', max_length=20)),
                ('magnitudes', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_templates', to='assets.assetgroupcomponent')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_templates', to='assets.assetgroupkind')),
            ],
            options={
                'ordering': ['number', 'axis'],
                'unique_together': {('kind', 'number', 'axis')},
            },
        ),
    ]
