# Generated by Django 5.2.17 on 2026-09-17 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_drop_legacy_kind_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroupcomponent',
            name='point_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='equipment',
            name='group_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='assets.assetgroupcomponent'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='order_in_group',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurementpoint',
            name='side',
            field=models.CharField(choices=[('free_end', 'Lado libre'), ('coupling_end', 'Lado acople'), ('opposite_coupling', 'Lado opuesto a acople'), ('inboard', 'Interior'), ('outboard', 'Exterior'), ('lower', 'Inferior'), ('upper', 'Superior'), ('custom', 'Otro')], default='custom', max_length=20),
        ),
    ]
