# Generated by Django 5.2.17 on 2026-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_builtin_kind_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lubrication_type',
            field=models.CharField(blank=True, choices=[('oil', 'Aceite'), ('grease', 'Grasa'), ('none', 'Ninguno')], max_length=10),
        ),
    ]
