# Generated by Django 5.2.17 on 2026-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_seed_lubrication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('motor', 'Motor'), ('pump', 'Bomba'), ('compressor', 'Compresor'), ('gearbox', 'Reductor'), ('fan', 'Ventilador'), ('blower', 'Soplador'), ('bearing_housing', 'Chumacera'), ('roller', 'Rodillo / polín'), ('other', 'Otro')], max_length=30),
        ),
    ]
