# Generated by Django 5.2.17 on 2026-09-17 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('core', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('technique_code', models.SlugField(blank=True, max_length=30)),
                ('typical_signature', models.CharField(blank=True, max_length=240)),
                ('iso_reference', models.CharField(blank=True, max_length=60)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('background', 'Antecedente'), ('observation', 'Observación'), ('failure_mode', 'Modo de falla'), ('finding', 'Hallazgo'), ('conclusion', 'Conclusión'), ('recommendation', 'Recomendación'), ('action_taken', 'Acción realizada'), ('note', 'Nota')], db_index=True, max_length=20)),
                ('entry_date', models.DateField(db_index=True)),
                ('text', models.TextField()),
                ('severity', models.PositiveSmallIntegerField(default=3, help_text='1 highest')),
                ('status', models.CharField(blank=True, choices=[('open', 'Abierta'), ('scheduled', 'Programada'), ('done', 'Ejecutada'), ('dismissed', 'Descartada')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tolerance_note', models.CharField(blank=True, help_text='e.g. "la pata coja no debe exceder 0.04 mm"', max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='assets.equipment')),
                ('service_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='services.servicevisit')),
                ('fault_modes', models.ManyToManyField(blank=True, related_name='entries', to='diagnostics.faultmode')),
            ],
            options={
                'ordering': ['-entry_date', 'entry_type'],
                'indexes': [models.Index(fields=['company', 'equipment', '-entry_date'], name='diagnostics_company_26b5cb_idx')],
            },
        ),
    ]
