# Generated by Django 5.2.17 on 2026-09-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultmode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faultmode',
            name='iso_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
